services:
  weather-service:
    build:
      context: ./weather-service
    ports:
      - "5000:5000"

  currency-service:
    build:
      context: ./currency-service
    ports:
      - "5001:5001"

  crypto-service:
    build:
      context: ./crypto-service
    ports:
      - "5002:5002"

  news-service:
    build:
      context: ./news-service
    ports:
      - "5003:5003"

  sports-service:
    build:
      context: ./sports-service
    ports:
      - "5004:5004"
